In [33]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# One Hot Encoding

Machine learning algorithms cannot work with categorical data directly.

Categorical data must be converted to numbers.

## What is One Hot Encoding?
A one hot encoding is a representation of categorical variables as binary vectors.

This first requires that the categorical values be mapped to integer values.

Then, each integer value is represented as a binary vector that is all zero values except the index of the integer, which is marked with a 1.

In [60]:
le = LabelEncoder()
ohe = OneHotEncoder(sparse=False)

# define example
data = ['zhot', 'cold', 'cold', 'warm', 'warm', 'hot', 'cold', 'cold', 'hot', 'hot']
df = pd.DataFrame(data, columns=['Temp_Categorical'])

# interget encode
integer_encoded = le.fit_transform(data)
print(integer_encoded)

df['Temp_Label_Encoded'] = integer_encoded

# binary encode
onehot_encoded = ohe.fit_transform(np.array(data).reshape(len(data),1))
print(onehot_encoded)
print(ohe.categories_)

df=pd.get_dummies(df,columns=['Temp_Categorical'])
df




[3 0 0 2 2 1 0 0 1 1]
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
[array(['cold', 'hot', 'warm', 'zhot'], dtype='<U4')]


Temp_Label_Encoded  Temp_Categorical_cold  Temp_Categorical_hot  \
0                   3                      0                     0   
1                   0                      1                     0   
2                   0                      1                     0   
3                   2                      0                     0   
4                   2                      0                     0   
5                   1                      0                     1   
6                   0                      1                     0   
7                   0                      1                     0   
8                   1                      0                     1   
9                   1                      0                     1   

   Temp_Categorical_warm  Temp_Categorical_zhot  
0                      0                      1  
1                      0                      0  
2                      0                      0  
3                      1                      0  
4                      1                      0  
5                      0                      0  
6                      0                      0  
7                      0                      0  
8                      0                      0  
9                      0                      0