# Linear Algebra

In [1]:
import numpy as np

# <u>Matrix and vector products</u>


# 1. numpy.dot
"multiply a matrix by another matrix"

In [2]:
# simple
res = np.dot(3,4)

print(res)

# (1, 2) • (7, 9) = 1×3 + 2×4 = 11 
res = np.dot([1,2],[3,4])

print(res)

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
res = np.dot(a, b)

print(res)

12
11
[[4 1]
 [2 2]]


# 2. numpy.vdot
"return the dot product of two vectors"

In [3]:
vec_a = np.arange(5)
vec_b = np.arange(5)+10

np.vdot(vec_a, vec_b)

130

# 3. numpy.inner
"inner product of two arrays"

without complex conjugation

In [4]:
vec_a = np.arange(5)
vec_b = np.arange(5)+10

np.inner(vec_a, vec_b)

130

# 4. numpy.outer
"computer the outer product of two vectors"
The outer product of two coordinate vectors is a matrix. 

The outer product contrasts with the dot product, which takes as input a pair of coordinate vectors and produces a scalar.

$\mathbf{v}\otimes\mathbf{w}$

and is defined as:

$\mathbf{v}\otimes\mathbf{w}:=\mathbf{v}\mathbf{w}^\top$



In [5]:
vec_a = np.arange(5)
vec_b = np.arange(5)+10

print(vec_a, vec_b)

res = np.outer(vec_a, vec_b)

print(res)

res = vec_b * (vec_a[:, np.newaxis])

print(res)

[0 1 2 3 4] [10 11 12 13 14]
[[ 0  0  0  0  0]
 [10 11 12 13 14]
 [20 22 24 26 28]
 [30 33 36 39 42]
 [40 44 48 52 56]]
[[ 0  0  0  0  0]
 [10 11 12 13 14]
 [20 22 24 26 28]
 [30 33 36 39 42]
 [40 44 48 52 56]]


# 5. numpy.matmul
"matrix product of two arrays"


In [6]:
a = np.array([[1,0],
               [0,1]])
b = np.array([[4,1],
               [2,2]])

np.matmul(a,b)

array([[4, 1],
       [2, 2]])

# 6. numpy.tensordot
"compute tensor produc along a specific axis"

Given two tensors, a and b, and an array_like object containing two array_like objects, (a_axes, b_axes), sum the products of a’s and b’s elements (components) over the axes specified by a_axes and b_axes. The third argument can be a single non-negative integer_like scalar, N; if it is such, then the last N dimensions of a and the first N dimensions of b are summed over.

axes = 0: tensor product $a\otimes b$

axes = 1: tensor product $a.b$

axes = 2: (default) tensor double contraction $a:b$

In [7]:
a = np.array([0,1,0,1])
a = a.reshape(2, 1,2)

A = np.array( ('a', 'z'), dtype=object )
A = A.reshape(1,2)

print (a, '\n\n', A)

np.tensordot(a, A)

[[[0 1]]

 [[0 1]]] 

 [['a' 'z']]


array(['z', 'z'], dtype=object)

# Scratch Area

In [40]:
a = np.array([1,2,3])
a.shape

b = np.array([(1,2),(3,4),(5,6)])
b.ravel()

c = np.full((10,10),999)
c.ravel()

d = np.linspace(0,10,100)

e = np.zeros((10,10))

y = np.random.random((3,2))
z = np.random.random((2,3))

print(b)
print('----')
print(b[0,1]) # select row 0, column 1
print('----')
print(b[2,0]) # select row 2, column 0
print('----')
print(b[0:3,0]) # select items 0 and 1 in column 1
print('----')
print(b[:1]) # select all items in row 0
print('----')
print(b[0:3, 1:2]) # select all items in row 0

a = [1,2,3,4]
d = [6,7,8,9]

np.column_stack((a,d))

np.vsplit(b,3)



[[1 2]
 [3 4]
 [5 6]]
----
2
----
5
----
[1 3 5]
----
[[1 2]]
----
[[2]
 [4]
 [6]]


[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]